// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnfmsopodocbceojqwvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZm1zb3BvZG9jYmNlb2pxd3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDk0MzgsImV4cCI6MjA1OTY4NTQzOH0.iUbbvENS1LaYN_Wa5GY2u26yKC_F2hUdvQQrjqWfdwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);